LangString addOrReinstall ${LANG_SIMPCHINESE} "添加 / 重新安装"
LangString alreadyInstalled ${LANG_SIMPCHINESE} "已安装"
LangString alreadyInstalledLong ${LANG_SIMPCHINESE} "${{productName}} 已安装。请选择操作后点击 $\"下一步$\" 继续。"
LangString appRunning ${LANG_SIMPCHINESE} "${{productName}} 正在运行。请先关闭应用后再继续。"
LangString appRunningOkKill ${LANG_SIMPCHINESE} "关闭应用并继续"
LangString chooseMaintenanceOption ${LANG_SIMPCHINESE} "选择维护选项。"
LangString confirmUninstall ${LANG_SIMPCHINESE} "确定要完全移除 ${{productName}} 及其组件吗？"
LangString deleteAppData ${LANG_SIMPCHINESE} "删除本地数据（设置、会话、API 密钥等）"
LangString dontUninstall ${LANG_SIMPCHINESE} "不卸载"
LangString installingWebview2 ${LANG_SIMPCHINESE} "正在安装 WebView2..."
LangString newerVersionInstalled ${LANG_SIMPCHINESE} "已安装更新版本。"
LangString olderOrEqualVersionInstalled ${LANG_SIMPCHINESE} "已安装相同或更新版本。"
LangString maintenanceHeader ${LANG_SIMPCHINESE} "维护选项"
LangString ok ${LANG_SIMPCHINESE} "确定"
LangString reinstall ${LANG_SIMPCHINESE} "重新安装"
LangString runAfterFinish ${LANG_SIMPCHINESE} "安装完成后运行 ${{productName}}"
LangString uninstall ${LANG_SIMPCHINESE} "卸载"
LangString uninstallApp ${LANG_SIMPCHINESE} "卸载 ${{productName}}"
